# alembic/versions/8a96e3ab3cfc_add_new_tables_for_ai_features.py
"""add new tables for ai features

Revision ID: 8a96e3ab3cfc
Revises: 
Create Date: 2026-01-17 12:40:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a96e3ab3cfc'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Ajouter la colonne user_id à sujets si elle n'existe pas
    try:
        op.add_column('sujets', sa.Column('user_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'sujets', 'users', ['user_id'], ['id'])
    except Exception:
        pass  # La colonne existe peut-être déjà
    
    # CORRECTION : Convertir la colonne preferences de TEXT à JSON
    op.execute("""
        ALTER TABLE user_preferences 
        ALTER COLUMN preferences TYPE JSON 
        USING CASE 
            WHEN preferences IS NULL OR preferences = '' THEN '{}'::json
            ELSE preferences::json 
        END
    """)
    
    # Ajouter la colonne original aux sujets si elle n'existe pas
    try:
        op.add_column('sujets', sa.Column('original', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    except Exception:
        pass
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Supprimer la colonne original
    try:
        op.drop_column('sujets', 'original')
    except Exception:
        pass
    
    # Revenir à TEXT pour preferences
    op.execute("""
        ALTER TABLE user_preferences 
        ALTER COLUMN preferences TYPE TEXT 
        USING preferences::text
    """)
    
    # Supprimer la contrainte et la colonne user_id
    try:
        op.drop_constraint(None, 'sujets', type_='foreignkey')
        op.drop_column('sujets', 'user_id')
    except Exception:
        pass
    
    # ### end Alembic commands ###