"""Saved3Subjects

Revision ID: ff9de67e0733
Revises: 8a96e3ab3cfc
Create Date: 2026-01-17 14:27:21.955505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9de67e0733'
down_revision: Union[str, Sequence[str], None] = '8a96e3ab3cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sujets', sa.Column('is_generated', sa.Boolean(), nullable=True))
    op.drop_column('sujets', 'original')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sujets', sa.Column('original', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('sujets', 'is_generated')
    # ### end Alembic commands ###
